# Generated by Django 5.1.4 on 2025-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0002_details_new_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_new',
            name='carted',
            field=models.BooleanField(default=False),
        ),
    ]
