# Generated by Django 5.1.4 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0003_details_new_carted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details_new',
            name='carted',
        ),
        migrations.AddField(
            model_name='menu_new',
            name='carted',
            field=models.BooleanField(default=False),
        ),
    ]
