# Generated by Django 5.1.4 on 2025-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatapp', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_new',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
